name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Fix APT
        run: |
          sudo rm -f /etc/apt/sources.list.d/*azure* /etc/apt/sources.list.d/*microsoft* /etc/apt/sources.list.d/*dotnet*
          sudo apt-get update -y
          sudo apt-get install -y bc bison flex libssl-dev libelf-dev build-essential clang lld llvm gcc-aarch64-linux-gnu

      - name: Fix KSU and Build
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          # agar KSU folder khali ho to usko fix karo
          if [ ! -s drivers/kernelsu/Kconfig ]; then
            echo "Creating dummy KSU to avoid build break"
            mkdir -p drivers/kernelsu
            echo 'config KSU' > drivers/kernelsu/Kconfig
            echo ' bool "KSU dummy"' >> drivers/kernelsu/Kconfig
            #
